@extends('layouts.auth', ['title' => 'EduSen | MFA Challenge'])

@section('content')
<div class="login_form">
    <div class="mfa_title">
        {{ __('Two-Factor Authentication') }}
    </div>
    <div class="mfa_caption">
        @if($mfa_method == 'email')
            {{ __('Please enter the 6-digit code sent to your email.') }}
        @else
            {{ __('Please enter the 6-digit code generated by your authenticator app.') }}
        @endif
    </div>
    <form method="POST" action="{{ route('mfa-challenge.verify') }}">
        @csrf
        <div class="form-group mb-3">
            <input id="pin" type="text" class="form-control mfa_pin" placeholder="123456" name="pin" required maxlength="6" pattern="\d{6}" autofocus autocomplete="one-time-code">
        </div>
        
        @error('pin')
            <div class="alert alert-danger mt-3">{{ $message }}</div>
        @enderror
        @if(session('error'))
            <div class="alert alert-danger mt-3">{{ session('error') }}</div>
        @endif
        
        <button id="login_btn" class="btn btn-lg btn-block mt-4 w-100" type="submit" style="color: #fff">{{ __('Verify') }}</button>
    </form>
    
    <div class="text-center mt-3">
         <form method="POST" action="{{ route('logout') }}">
            @csrf
            <button type="submit" class="btn btn-link back_to_login"><i class="fas fa-arrow-left"></i> {{ __('Back to Login') }}</button>
        </form>
    </div>
</div>
@endsection